name: Maven CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B clean install
      
    - name: Sleep for 10 seconds
      run: sleep 10
      
    - name: Run tests from mainTests class
      run: mvn -Dtest=mainTests test
